### ISSUE TITLE
Using AnimatePresence

### ISSUE THREAD

**Issue by arjarn** [micha-lmxt/svelte-motion#5]
I'm having problem for using AnimatePresence with multiple elements and delay...

Example here :

https://svelte.dev/repl/b66d0893bb4d4e9da47cd1ea29cacef1?version=3.38.2

Animate with "turn" button working very well.
But with add button (add element in the list), it seem exit variant is not triggering : all elements disappears without transition I define in variant.

Sure it may be silly thing but hurting my brain :-/

**Comment by micha-lmxt** [comment]
Hi, 

the problem has a simple fix: update all imports to the latest version, either by removing the @0.x.x parts or seeing it to 'svelte-motion@0.11.1'. 

I always set these, because there sometimes it's a delay when you just publish a new version. 'AnimatePresence' got a major bug fix recently (which also hurted my brain :) ).

Also, 'AnimatePresence' has a prop ( not well documented at the moment) 'exitBeforeEnter' (boolean), which you could try.

**Comment by arjarn** [comment]
Adding exitBeforeEnter on correct version and all is perfect ! 👍 

Thanx again. 
I'm closing this issue...
